/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/accounts': RouteRecordInfo<'/accounts', '/accounts', Record<never, never>, Record<never, never>>,
    '/balances': RouteRecordInfo<'/balances', '/balances', Record<never, never>, Record<never, never>>,
    '/enter': RouteRecordInfo<'/enter', '/enter', Record<never, never>, Record<never, never>>,
    '/exit': RouteRecordInfo<'/exit', '/exit', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/loans': RouteRecordInfo<'/loans', '/loans', Record<never, never>, Record<never, never>>,
    '/savings': RouteRecordInfo<'/savings', '/savings', Record<never, never>, Record<never, never>>,
    '/transactions': RouteRecordInfo<'/transactions', '/transactions', Record<never, never>, Record<never, never>>,
    '/welcome': RouteRecordInfo<'/welcome', '/welcome', Record<never, never>, Record<never, never>>,
  }
}
