/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/[username]': RouteRecordInfo<
      '/[username]',
      '/:username',
      { username: ParamValue<true> },
      { username: ParamValue<false> },
      | never
    >,
    '/agents': RouteRecordInfo<
      '/agents',
      '/agents',
      Record<never, never>,
      Record<never, never>,
      | '/agents/'
      | '/agents/[id]'
    >,
    '/agents/': RouteRecordInfo<
      '/agents/',
      '/agents',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/agents/[id]': RouteRecordInfo<
      '/agents/[id]',
      '/agents/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/changelog': RouteRecordInfo<
      '/changelog',
      '/changelog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/code': RouteRecordInfo<
      '/code',
      '/code',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/create': RouteRecordInfo<
      '/create',
      '/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/enter': RouteRecordInfo<
      '/enter',
      '/enter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/exit': RouteRecordInfo<
      '/exit',
      '/exit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/explore': RouteRecordInfo<
      '/explore',
      '/explore',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home': RouteRecordInfo<
      '/home',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/invitations': RouteRecordInfo<
      '/invitations',
      '/invitations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/maps': RouteRecordInfo<
      '/maps',
      '/maps',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/new': RouteRecordInfo<
      '/new',
      '/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pricing': RouteRecordInfo<
      '/pricing',
      '/pricing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile': RouteRecordInfo<
      '/profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/runs': RouteRecordInfo<
      '/runs',
      '/runs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/start': RouteRecordInfo<
      '/start',
      '/start',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tasks': RouteRecordInfo<
      '/tasks',
      '/tasks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/teams/': RouteRecordInfo<
      '/teams/',
      '/teams',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/teams/[teamId]': RouteRecordInfo<
      '/teams/[teamId]',
      '/teams/:teamId',
      { teamId: ParamValue<true> },
      { teamId: ParamValue<false> },
      | never
    >,
    '/test': RouteRecordInfo<
      '/test',
      '/test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/welcome': RouteRecordInfo<
      '/welcome',
      '/welcome',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/write': RouteRecordInfo<
      '/write',
      '/write',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/[username].vue': {
      routes:
        | '/[username]'
      views:
        | never
    }
    'src/pages/agents.vue': {
      routes:
        | '/agents'
        | '/agents/'
        | '/agents/[id]'
      views:
        | 'default'
    }
    'src/pages/agents/index.vue': {
      routes:
        | '/agents/'
      views:
        | never
    }
    'src/pages/agents/[id].vue': {
      routes:
        | '/agents/[id]'
      views:
        | never
    }
    'src/pages/changelog.vue': {
      routes:
        | '/changelog'
      views:
        | never
    }
    'src/pages/code.vue': {
      routes:
        | '/code'
      views:
        | never
    }
    'src/pages/create.vue': {
      routes:
        | '/create'
      views:
        | never
    }
    'src/pages/enter.vue': {
      routes:
        | '/enter'
      views:
        | never
    }
    'src/pages/exit.vue': {
      routes:
        | '/exit'
      views:
        | never
    }
    'src/pages/explore.vue': {
      routes:
        | '/explore'
      views:
        | never
    }
    'src/pages/home.vue': {
      routes:
        | '/home'
      views:
        | never
    }
    'src/pages/invitations.vue': {
      routes:
        | '/invitations'
      views:
        | never
    }
    'src/pages/maps.vue': {
      routes:
        | '/maps'
      views:
        | never
    }
    'src/pages/new.vue': {
      routes:
        | '/new'
      views:
        | never
    }
    'src/pages/pricing.vue': {
      routes:
        | '/pricing'
      views:
        | never
    }
    'src/pages/profile.vue': {
      routes:
        | '/profile'
      views:
        | never
    }
    'src/pages/runs.vue': {
      routes:
        | '/runs'
      views:
        | never
    }
    'src/pages/start.vue': {
      routes:
        | '/start'
      views:
        | never
    }
    'src/pages/tasks.vue': {
      routes:
        | '/tasks'
      views:
        | never
    }
    'src/pages/teams/index.vue': {
      routes:
        | '/teams/'
      views:
        | never
    }
    'src/pages/teams/[teamId].vue': {
      routes:
        | '/teams/[teamId]'
      views:
        | never
    }
    'src/pages/test.vue': {
      routes:
        | '/test'
      views:
        | never
    }
    'src/pages/welcome.vue': {
      routes:
        | '/welcome'
      views:
        | never
    }
    'src/pages/write.vue': {
      routes:
        | '/write'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
