/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/agents': RouteRecordInfo<'/agents', '/agents', Record<never, never>, Record<never, never>, '/agents/' | '/agents/[id]'>,
    '/agents/': RouteRecordInfo<'/agents/', '/agents', Record<never, never>, Record<never, never>>,
    '/agents/[id]': RouteRecordInfo<'/agents/[id]', '/agents/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/changelog': RouteRecordInfo<'/changelog', '/changelog', Record<never, never>, Record<never, never>>,
    '/create': RouteRecordInfo<'/create', '/create', Record<never, never>, Record<never, never>>,
    '/enter': RouteRecordInfo<'/enter', '/enter', Record<never, never>, Record<never, never>>,
    '/exit': RouteRecordInfo<'/exit', '/exit', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/pricing': RouteRecordInfo<'/pricing', '/pricing', Record<never, never>, Record<never, never>>,
    '/runs': RouteRecordInfo<'/runs', '/runs', Record<never, never>, Record<never, never>>,
    '/tasks': RouteRecordInfo<'/tasks', '/tasks', Record<never, never>, Record<never, never>>,
    '/teams': RouteRecordInfo<'/teams', '/teams', Record<never, never>, Record<never, never>>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
    '/welcome': RouteRecordInfo<'/welcome', '/welcome', Record<never, never>, Record<never, never>>,
  }
}
