<script lang="ts" setup>
import { BotChatContextKey, useBotChat } from "@/composables/useBotChat"
import { isTauri } from "@/composables/usePlatform"
import { usePopout } from "@/composables/usePopout"
import { IconPictureInPicture } from "@/data/icons"
import { openAiAskPopoutWindow } from "@/modules/aiAskPopout"

const { t } = useI18n()

// Same independent-context pattern as `AiAsk.vue` and the `/ask` window:
// the pop-out owns its chat for as long as it's open, separate from the
// bot page's context. `pinnedContext` keeps the chat from being reset by
// global team/workspace re-settles while it floats.
const botChat = useBotChat({ pinnedContext: true })
provide(BotChatContextKey, botChat)

const { isPoppedOut, poppedOutSessionId, poppedOutTitle } = usePopout()

// `selectSession` waits for team/workspace internally, so firing it from
// setup (immediate) is safe on a cold boot. Watching the id means
// clicking another pinned chat swaps this window's content in place.
watch(
  poppedOutSessionId,
  (id) => {
    if (id) void botChat.selectSession(id)
  },
  { immediate: true }
)

// Keep the window-chrome title honest: `openChatInPopout` seeds it from
// the chip that was clicked, but a rename (or the title generated by the
// first turn of a fresh chat) should follow. Also means the title handed
// to a native pop-out below is current.
watch(
  () => botChat.activeSession.value?.title,
  (title) => {
    if (title) poppedOutTitle.value = title
  }
)

// Promote the in-app floating panel to a real detached OS window, the
// same handoff `bot.vue` and `AiAsk.vue` do. One-way and one-for-one:
// the panel closes, because leaving both open would show the same chat
// twice with no way to tell which one is which.
const popOutToWindow = () => {
  openAiAskPopoutWindow({
    sessionId: botChat.sessionId.value ?? poppedOutSessionId.value,
    title: poppedOutTitle.value || t("pages.start.askAi"),
  })
  isPoppedOut.value = false
}
</script>

<template>
  <Teleport v-if="isTauri" defer to="#popout-actions">
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger as-child>
          <InputGroupButton
            variant="ghost"
            size="icon-xs"
            @click="popOutToWindow"
          >
            <IconPictureInPicture />
          </InputGroupButton>
        </TooltipTrigger>
        <TooltipContent>{{ t("ai.openInNewWindow") }}</TooltipContent>
      </Tooltip>
    </TooltipProvider>
  </Teleport>
  <AiChatShell />
</template>
