import {
  ACCENT_FAMILIES,
  ANCHOR_FAMILY,
  BASE_FAMILIES,
  paletteVar,
  type AccentFamily,
  type BaseFamily,
} from "../../utils/theme/families"
import {
  buildBaseTokens,
  paletteColor,
  pickContrastVar,
  type BaseSourceToken,
} from "../../utils/theme/tokens"

export type ThemeMode = "light" | "dark"

const LIGHT_MODE: ThemeMode = "light"
const DARK_MODE: ThemeMode = "dark"

const FONT_TOKENS = {
  sans: '"Geist Variable", "sans-serif"',
  serif: '"Bricolage Grotesque Variable", "serif"',
  mono: '"Geist Mono Variable", "monospace"',
} as const

const SIZE_TOKENS = {
  xs: "var(--text-xs)",
  sm: "var(--text-sm)",
  base: "var(--text-base)",
  lg: "var(--text-lg)",
  xl: "var(--text-xl)",
} as const

const LIGHT_ACCENT_SHADES = {
  primary: 300,
  destructive: 400,
  ring: 400,
  charts: [300, 500, 700, 800, 900],
} as const
const DARK_ACCENT_SHADES = {
  primary: 700,
  destructive: 600,
  ring: 600,
  charts: [700, 500, 300, 200, 100],
} as const

type ThemeTokens = Record<string, string>

// Per-source-token palette shades for the two base renderers. Both expand
// through the shared `buildBaseTokens` graph, so only the source values (and,
// for presets, the white/black background) differ between them.
const PRESET_SOURCE_SHADES = {
  light: {
    foreground: 800,
    card: 50,
    "card-foreground": 900,
    secondary: 100,
    muted: 200,
    "muted-foreground": 600,
  },
  dark: {
    foreground: 200,
    card: 950,
    "card-foreground": 100,
    secondary: 900,
    muted: 800,
    "muted-foreground": 400,
  },
} satisfies Record<
  ThemeMode,
  Record<Exclude<BaseSourceToken, "background">, number>
>

const ACCENT_BASE_SOURCE_SHADES = {
  light: {
    background: 50,
    foreground: 950,
    card: 100,
    "card-foreground": 950,
    secondary: 100,
    muted: 200,
    "muted-foreground": 600,
  },
  dark: {
    background: 950,
    foreground: 50,
    card: 900,
    "card-foreground": 100,
    secondary: 900,
    muted: 800,
    "muted-foreground": 400,
  },
} satisfies Record<ThemeMode, Record<BaseSourceToken, number>>

// Preset base: the active base family's shades on white/black surfaces.
export function buildPresetBaseTokens(
  family: BaseFamily,
  mode: ThemeMode
): ThemeTokens {
  const shades = PRESET_SOURCE_SHADES[mode]

  return buildBaseTokens(
    (token) =>
      token === "background"
        ? mode === LIGHT_MODE
          ? "var(--color-white)"
          : "var(--color-black)"
        : paletteVar(family, shades[token]),
    (target) => `var(--${target})`
  )
}

// Accent-as-base (`data-base="accent"`): an accent family tinting every
// surface, so the background itself carries the hue.
export function buildAccentBaseTokens(
  family: AccentFamily,
  mode: ThemeMode
): ThemeTokens {
  const shades = ACCENT_BASE_SOURCE_SHADES[mode]

  return buildBaseTokens(
    (token) => paletteVar(family, shades[token]),
    (target) => `var(--${target})`
  )
}

export function buildAccentTokens(
  family: AccentFamily | BaseFamily,
  mode: ThemeMode
): ThemeTokens {
  const shades = mode === LIGHT_MODE ? LIGHT_ACCENT_SHADES : DARK_ACCENT_SHADES
  const primary = paletteColor(family, shades.primary)
  const destructive = paletteColor(family, shades.destructive)

  return {
    "--primary": paletteVar(family, shades.primary),
    "--primary-foreground": pickContrastVar(primary),
    "--destructive": paletteVar(family, shades.destructive),
    "--destructive-foreground": pickContrastVar(destructive),
    "--ring": paletteVar(family, shades.ring),
    "--sidebar-ring": paletteVar(family, shades.ring),
    "--chart-1": paletteVar(family, shades.charts[0]),
    "--chart-2": paletteVar(family, shades.charts[1]),
    "--chart-3": paletteVar(family, shades.charts[2]),
    "--chart-4": paletteVar(family, shades.charts[3]),
    "--chart-5": paletteVar(family, shades.charts[4]),
  }
}

export function generateThemeCss() {
  const sections = [
    "/* Generated by src/plugins/theme/generateThemesCssPlugin.ts. Do not edit by hand. */",
    "@layer base {",
    indent(serializeBlock(":root", buildRootFallbackTokens())),
    "",
    indent(comment("Typography & Scale")),
    ...Object.entries(FONT_TOKENS).flatMap(([fontId, value]) => [
      indent(
        serializeBlock(`:root[data-font="${fontId}"]`, { "--flex": value })
      ),
      "",
    ]),
    ...Object.entries(SIZE_TOKENS).flatMap(([sizeId, value]) => [
      indent(
        serializeBlock(`:root[data-size="${sizeId}"]`, { "--size": value })
      ),
      "",
    ]),
    indent(comment("Theme Scheme")),
    indent(
      serializeBlock(':root[data-theme="light"]', { "color-scheme": "light" })
    ),
    "",
    indent(
      serializeBlock(':root[data-theme="dark"]', { "color-scheme": "dark" })
    ),
    "",
    indent(comment("Preset Base Palettes")),
    ...BASE_FAMILIES.flatMap((family) => [
      indent(
        serializeBlock(
          `:root[data-theme="light"][data-base="${family}"]`,
          buildPresetBaseTokens(family, LIGHT_MODE)
        )
      ),
      "",
      indent(
        serializeBlock(
          `:root[data-theme="dark"][data-base="${family}"]`,
          buildPresetBaseTokens(family, DARK_MODE)
        )
      ),
      "",
    ]),
    indent(comment("Preset Accent Tokens")),
    ...ACCENT_FAMILIES.flatMap((family) => [
      indent(
        serializeBlock(
          `:root[data-theme="light"][data-accent="${family}"]`,
          buildAccentTokens(family, LIGHT_MODE)
        )
      ),
      "",
      indent(
        serializeBlock(
          `:root[data-theme="dark"][data-accent="${family}"]`,
          buildAccentTokens(family, DARK_MODE)
        )
      ),
      "",
    ]),
    indent(comment('Base Accent Tokens (`data-accent="base"`)')),
    ...BASE_FAMILIES.flatMap((family) => [
      indent(
        serializeBlock(
          `:root[data-theme="light"][data-base="${family}"][data-accent="base"]`,
          buildAccentTokens(family, LIGHT_MODE)
        )
      ),
      "",
      indent(
        serializeBlock(
          `:root[data-theme="dark"][data-base="${family}"][data-accent="base"]`,
          buildAccentTokens(family, DARK_MODE)
        )
      ),
      "",
    ]),
    indent(comment('Accent Base Palettes (`data-base="accent"`)')),
    ...ACCENT_FAMILIES.flatMap((family) => [
      indent(
        serializeBlock(
          `:root[data-theme="light"][data-base="accent"][data-accent="${family}"]`,
          buildAccentBaseTokens(family, LIGHT_MODE)
        )
      ),
      "",
      indent(
        serializeBlock(
          `:root[data-theme="dark"][data-base="accent"][data-accent="${family}"]`,
          buildAccentBaseTokens(family, DARK_MODE)
        )
      ),
      "",
    ]),
  ]

  return `${trimTrailingEmptyLines(sections).join("\n")}\n}\n`
}

function buildRootFallbackTokens(): ThemeTokens {
  return {
    "--flex": FONT_TOKENS.sans,
    "--size": SIZE_TOKENS.base,
    "color-scheme": "light",
    ...buildPresetBaseTokens(ANCHOR_FAMILY, LIGHT_MODE),
    ...buildAccentTokens(ANCHOR_FAMILY, LIGHT_MODE),
  }
}

function comment(title: string) {
  return `/* ${title} */`
}

function serializeBlock(selector: string, declarations: ThemeTokens) {
  const lines = [`${selector} {`]
  let previousWasCustomProperty: boolean | null = null

  for (const [name, value] of Object.entries(declarations)) {
    const isCustomProperty = name.startsWith("--")

    if (
      previousWasCustomProperty !== null &&
      previousWasCustomProperty !== isCustomProperty
    ) {
      lines.push("")
    }

    lines.push(`  ${name}: ${value};`)
    previousWasCustomProperty = isCustomProperty
  }

  lines.push("}")

  return lines.join("\n")
}

function indent(value: string) {
  return value
    .split("\n")
    .map((line) => (line ? `  ${line}` : line))
    .join("\n")
}

function trimTrailingEmptyLines(lines: string[]) {
  const trimmed = [...lines]

  while (trimmed.at(-1) === "") {
    trimmed.pop()
  }

  return trimmed
}
