import colors from "tailwindcss/colors"

export type ThemeMode = "light" | "dark"

const LIGHT_MODE: ThemeMode = "light"
const DARK_MODE: ThemeMode = "dark"

const BASE_FAMILIES = [
  "slate",
  "gray",
  "zinc",
  "neutral",
  "stone",
  "taupe",
  "mauve",
  "mist",
  "olive",
] as const

const ACCENT_FAMILIES = [
  "red",
  "orange",
  "amber",
  "yellow",
  "lime",
  "green",
  "emerald",
  "teal",
  "cyan",
  "sky",
  "blue",
  "indigo",
  "violet",
  "purple",
  "fuchsia",
  "pink",
  "rose",
] as const

const FONT_TOKENS = {
  sans: '"Geist Variable", "sans-serif"',
  serif: '"EB Garamond Variable", "serif"',
  mono: '"Geist Mono Variable", "monospace"',
} as const

const SIZE_TOKENS = {
  xs: "var(--text-xs)",
  sm: "var(--text-sm)",
  base: "var(--text-base)",
  lg: "var(--text-lg)",
  xl: "var(--text-xl)",
} as const

const DEFAULT_BASE_FAMILY = "neutral"
const LIGHT_CONTRAST_COLOR = readPaletteColor(DEFAULT_BASE_FAMILY, 50)
const LIGHT_CONTRAST_CSS_VALUE = paletteVar(DEFAULT_BASE_FAMILY, 50)
const DARK_CONTRAST_COLOR = readPaletteColor(DEFAULT_BASE_FAMILY, 950)
const DARK_CONTRAST_CSS_VALUE = paletteVar(DEFAULT_BASE_FAMILY, 950)
const LIGHT_ACCENT_SHADES = {
  primary: 300,
  destructive: 200,
  ring: 400,
  charts: [300, 500, 700, 800, 900],
} as const
const DARK_ACCENT_SHADES = {
  primary: 700,
  destructive: 800,
  ring: 600,
  charts: [700, 500, 300, 200, 100],
} as const

type ThemeTokens = Record<string, string>

export function buildPresetBaseTokens(
  family: (typeof BASE_FAMILIES)[number],
  mode: ThemeMode
): ThemeTokens {
  if (mode === LIGHT_MODE) {
    const background = "var(--color-white)"
    const foreground = paletteVar(family, 800)
    const card = paletteVar(family, 50)
    const cardForeground = paletteVar(family, 900)
    const secondary = paletteVar(family, 100)
    const muted = paletteVar(family, 200)

    return buildBaseTokenShape({
      background,
      foreground,
      card,
      cardForeground,
      secondary,
      muted,
      mutedForeground: paletteVar(family, 600),
    })
  }

  const background = "var(--color-black)"
  const foreground = paletteVar(family, 200)
  const card = paletteVar(family, 950)
  const cardForeground = paletteVar(family, 100)
  const secondary = paletteVar(family, 900)
  const muted = paletteVar(family, 800)

  return buildBaseTokenShape({
    background,
    foreground,
    card,
    cardForeground,
    secondary,
    muted,
    mutedForeground: paletteVar(family, 400),
  })
}

export function buildAccentBaseTokens(
  family: (typeof ACCENT_FAMILIES)[number],
  mode: ThemeMode
): ThemeTokens {
  if (mode === LIGHT_MODE) {
    const background = paletteVar(family, 50)
    const foreground = paletteVar(family, 950)
    const card = paletteVar(family, 100)
    const cardForeground = paletteVar(family, 950)
    const secondary = paletteVar(family, 100)
    const muted = paletteVar(family, 200)

    return buildBaseTokenShape({
      background,
      foreground,
      card,
      cardForeground,
      secondary,
      muted,
      mutedForeground: paletteVar(family, 600),
    })
  }

  const background = paletteVar(family, 950)
  const foreground = paletteVar(family, 50)
  const card = paletteVar(family, 900)
  const cardForeground = paletteVar(family, 100)
  const secondary = paletteVar(family, 900)
  const muted = paletteVar(family, 800)

  return buildBaseTokenShape({
    background,
    foreground,
    card,
    cardForeground,
    secondary,
    muted,
    mutedForeground: paletteVar(family, 400),
  })
}

export function buildAccentTokens(
  family: (typeof ACCENT_FAMILIES)[number] | (typeof BASE_FAMILIES)[number],
  mode: ThemeMode
): ThemeTokens {
  const shades = mode === LIGHT_MODE ? LIGHT_ACCENT_SHADES : DARK_ACCENT_SHADES
  const primary = readPaletteColor(family, shades.primary)
  const destructive = readPaletteColor(family, shades.destructive)

  return {
    "--primary": paletteVar(family, shades.primary),
    "--primary-foreground": pickContrastCssValue(primary),
    "--destructive": paletteVar(family, shades.destructive),
    "--destructive-foreground": pickContrastCssValue(destructive),
    "--ring": paletteVar(family, shades.ring),
    "--sidebar-ring": paletteVar(family, shades.ring),
    "--chart-1": paletteVar(family, shades.charts[0]),
    "--chart-2": paletteVar(family, shades.charts[1]),
    "--chart-3": paletteVar(family, shades.charts[2]),
    "--chart-4": paletteVar(family, shades.charts[3]),
    "--chart-5": paletteVar(family, shades.charts[4]),
  }
}

export function generateThemeCss() {
  const sections = [
    "/* Generated by src/plugins/theme/generateThemesCssPlugin.ts. Do not edit by hand. */",
    "@layer base {",
    indent(serializeBlock(":root", buildRootFallbackTokens())),
    "",
    indent(comment("Typography & Scale")),
    ...Object.entries(FONT_TOKENS).flatMap(([fontId, value]) => [
      indent(
        serializeBlock(`:root[data-font="${fontId}"]`, { "--flex": value })
      ),
      "",
    ]),
    ...Object.entries(SIZE_TOKENS).flatMap(([sizeId, value]) => [
      indent(
        serializeBlock(`:root[data-size="${sizeId}"]`, { "--size": value })
      ),
      "",
    ]),
    indent(comment("Theme Scheme")),
    indent(
      serializeBlock(':root[data-theme="light"]', { "color-scheme": "light" })
    ),
    "",
    indent(
      serializeBlock(':root[data-theme="dark"]', { "color-scheme": "dark" })
    ),
    "",
    indent(comment("Preset Base Palettes")),
    ...BASE_FAMILIES.flatMap((family) => [
      indent(
        serializeBlock(
          `:root[data-theme="light"][data-base="${family}"]`,
          buildPresetBaseTokens(family, LIGHT_MODE)
        )
      ),
      "",
      indent(
        serializeBlock(
          `:root[data-theme="dark"][data-base="${family}"]`,
          buildPresetBaseTokens(family, DARK_MODE)
        )
      ),
      "",
    ]),
    indent(comment("Preset Accent Tokens")),
    ...ACCENT_FAMILIES.flatMap((family) => [
      indent(
        serializeBlock(
          `:root[data-theme="light"][data-accent="${family}"]`,
          buildAccentTokens(family, LIGHT_MODE)
        )
      ),
      "",
      indent(
        serializeBlock(
          `:root[data-theme="dark"][data-accent="${family}"]`,
          buildAccentTokens(family, DARK_MODE)
        )
      ),
      "",
    ]),
    indent(comment('Base Accent Tokens (`data-accent="base"`)')),
    ...BASE_FAMILIES.flatMap((family) => [
      indent(
        serializeBlock(
          `:root[data-theme="light"][data-base="${family}"][data-accent="base"]`,
          buildAccentTokens(family, LIGHT_MODE)
        )
      ),
      "",
      indent(
        serializeBlock(
          `:root[data-theme="dark"][data-base="${family}"][data-accent="base"]`,
          buildAccentTokens(family, DARK_MODE)
        )
      ),
      "",
    ]),
    indent(comment('Accent Base Palettes (`data-base="accent"`)')),
    ...ACCENT_FAMILIES.flatMap((family) => [
      indent(
        serializeBlock(
          `:root[data-theme="light"][data-base="accent"][data-accent="${family}"]`,
          buildAccentBaseTokens(family, LIGHT_MODE)
        )
      ),
      "",
      indent(
        serializeBlock(
          `:root[data-theme="dark"][data-base="accent"][data-accent="${family}"]`,
          buildAccentBaseTokens(family, DARK_MODE)
        )
      ),
      "",
    ]),
    "}",
  ]

  return `${trimTrailingEmptyLines(sections).join("\n")}\n`
}

function buildRootFallbackTokens(): ThemeTokens {
  return {
    "--flex": FONT_TOKENS.sans,
    "--size": SIZE_TOKENS.base,
    "color-scheme": "light",
    ...buildPresetBaseTokens(DEFAULT_BASE_FAMILY, LIGHT_MODE),
    ...buildAccentTokens(DEFAULT_BASE_FAMILY, LIGHT_MODE),
  }
}

function buildBaseTokenShape({
  background,
  foreground,
  card,
  cardForeground,
  secondary,
  muted,
  mutedForeground,
}: {
  background: string
  foreground: string
  card: string
  cardForeground: string
  secondary: string
  muted: string
  mutedForeground: string
}): ThemeTokens {
  return {
    "--background": background,
    "--foreground": foreground,
    "--card": card,
    "--card-foreground": cardForeground,
    "--popover": "var(--background)",
    "--popover-foreground": "var(--foreground)",
    "--secondary": secondary,
    "--secondary-foreground": "var(--foreground)",
    "--muted": muted,
    "--muted-foreground": mutedForeground,
    "--accent": "var(--muted)",
    "--accent-foreground": "var(--card-foreground)",
    "--border": "var(--muted)",
    "--input": "var(--muted)",
    "--sidebar": "var(--card)",
    "--sidebar-foreground": "var(--card-foreground)",
    "--sidebar-primary": "var(--foreground)",
    "--sidebar-primary-foreground": "var(--card)",
    "--sidebar-accent": "var(--muted)",
    "--sidebar-accent-foreground": "var(--card-foreground)",
    "--sidebar-border": "var(--muted)",
  }
}

function comment(title: string) {
  return `/* ${title} */`
}

function serializeBlock(selector: string, declarations: ThemeTokens) {
  const lines = [`${selector} {`]
  let previousWasCustomProperty: boolean | null = null

  for (const [name, value] of Object.entries(declarations)) {
    const isCustomProperty = name.startsWith("--")

    if (
      previousWasCustomProperty !== null &&
      previousWasCustomProperty !== isCustomProperty
    ) {
      lines.push("")
    }

    lines.push(`  ${name}: ${value};`)
    previousWasCustomProperty = isCustomProperty
  }

  lines.push("}")

  return lines.join("\n")
}

function indent(value: string) {
  return value
    .split("\n")
    .map((line) => (line ? `  ${line}` : line))
    .join("\n")
}

function trimTrailingEmptyLines(lines: string[]) {
  const trimmed = [...lines]

  while (trimmed.at(-1) === "") {
    trimmed.pop()
  }

  return trimmed
}

function paletteVar(
  family: (typeof BASE_FAMILIES)[number] | (typeof ACCENT_FAMILIES)[number],
  shade: number
) {
  return `var(--color-${family}-${shade})`
}

function readPaletteColor(
  family: (typeof BASE_FAMILIES)[number] | (typeof ACCENT_FAMILIES)[number],
  shade: number
) {
  const familyPalette = colors[family] as Record<number, string> | undefined
  const value = familyPalette?.[shade]

  if (typeof value !== "string") {
    throw new Error(`Missing Tailwind color for ${family}-${shade}`)
  }

  return value
}

function pickContrastCssValue(color: string) {
  return getContrastRatio(color, LIGHT_CONTRAST_COLOR) >=
    getContrastRatio(color, DARK_CONTRAST_COLOR)
    ? LIGHT_CONTRAST_CSS_VALUE
    : DARK_CONTRAST_CSS_VALUE
}

function getContrastRatio(colorA: string, colorB: string) {
  const luminanceA = getRelativeLuminance(colorA)
  const luminanceB = getRelativeLuminance(colorB)
  const lighter = Math.max(luminanceA, luminanceB)
  const darker = Math.min(luminanceA, luminanceB)

  return (lighter + 0.05) / (darker + 0.05)
}

function getRelativeLuminance(color: string) {
  const { r, g, b } = parseCssColor(color)

  return (
    0.2126 * channelToLinear(r / 255) +
    0.7152 * channelToLinear(g / 255) +
    0.0722 * channelToLinear(b / 255)
  )
}

function parseCssColor(value: string) {
  if (value.startsWith("#")) {
    return hexToRgb(value)
  }

  if (value.startsWith("oklch(")) {
    return oklchToRgb(value)
  }

  throw new Error(`Unsupported color format: ${value}`)
}

function hexToRgb(hex: string) {
  const normalized = normalizeHex(hex)
  const value = Number.parseInt(normalized.slice(1), 16)

  return {
    r: (value >> 16) & 0xff,
    g: (value >> 8) & 0xff,
    b: value & 0xff,
  }
}

function normalizeHex(value: string) {
  const normalized = value.toLowerCase()

  if (/^#[0-9a-f]{3}$/.test(normalized)) {
    return `#${normalized[1]}${normalized[1]}${normalized[2]}${normalized[2]}${normalized[3]}${normalized[3]}`
  }

  if (/^#[0-9a-f]{6}$/.test(normalized)) {
    return normalized
  }

  throw new Error(`Invalid hex color: ${value}`)
}

function oklchToRgb(value: string) {
  const match =
    /^oklch\(([\d.]+)%\s+([\d.]+)\s+(-?[\d.]+)(?:\s*\/\s*[\d.]+)?\)$/.exec(
      value
    )

  if (!match) {
    throw new Error(`Invalid OKLCH color: ${value}`)
  }

  const lightness = Number.parseFloat(match[1]) / 100
  const chroma = Number.parseFloat(match[2])
  const hueRadians = (Number.parseFloat(match[3]) * Math.PI) / 180
  const a = chroma * Math.cos(hueRadians)
  const b = chroma * Math.sin(hueRadians)

  const l = lightness + 0.3963377774 * a + 0.2158037573 * b
  const m = lightness - 0.1055613458 * a - 0.0638541728 * b
  const s = lightness - 0.0894841775 * a - 1.291485548 * b
  const lCube = l ** 3
  const mCube = m ** 3
  const sCube = s ** 3

  return {
    r: linearChannelToRgb(
      +4.0767416621 * lCube - 3.3077115913 * mCube + 0.2309699292 * sCube
    ),
    g: linearChannelToRgb(
      -1.2684380046 * lCube + 2.6097574011 * mCube - 0.3413193965 * sCube
    ),
    b: linearChannelToRgb(
      -0.0041960863 * lCube - 0.7034186147 * mCube + 1.707614701 * sCube
    ),
  }
}

function linearChannelToRgb(value: number) {
  const clipped = Math.min(1, Math.max(0, value))
  const gammaCorrected =
    clipped <= 0.0031308
      ? 12.92 * clipped
      : 1.055 * clipped ** (1 / 2.4) - 0.055

  return Math.round(gammaCorrected * 255)
}

function channelToLinear(value: number) {
  if (value <= 0.04045) return value / 12.92
  return ((value + 0.055) / 1.055) ** 2.4
}
